---
title: "HW1_Rodolfo_Urbano_ggpot2exercise"
author: "Rodolfo Urbano"
date: "Saturday, January 17, 2015"
output: html_document
---


```{r echo=FALSE}
#Show the first few lines of the iris data.
head(iris)
#Data needs to be reshaped. I was long and contained Length and Width measurements of for plant parts (Petal & Sepal) as separate columns. Measurement will be merged and plant part information provided as a value in a new column.
```

```{r echo=FALSE}
#load reshape 2 package
library(reshape2)
#create a new column that we will need
iris$Flower_id <- rownames(iris)
head(iris)
iris_melted <- melt(iris)
head(iris_melted)
split_variable <- strsplit(as.character(iris_melted$variable), split = "\\.")
iris_melted$flower_part <- sapply(split_variable, "[", 1)
iris_melted$measurement_type <- sapply(split_variable, "[", 2)
iris_melted$variable <- NULL
head(iris_melted)
iris_cast <- dcast(iris_melted, formula = Flower_id + Species + flower_part ~ measurement_type)
head(iris_cast)

library(ggplot2)
ggplot(data=iris_cast, aes(x=Width, y=Length))+ # Add points and use free scales in the facet
  geom_point()+facet_grid(Species~flower_part, scale="free")+
  # Add a regression line
  geom_smooth(method="lm")+
  # Use the black/white theme and increase the font size
  theme_bw(base_size=24)

```

